spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hsu_learn
    username: root
    password: MINHyuck0122@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  web:
    error:
      include-message: always
server:
  port: 8080